### ISSUE TITLE
"Build from sources" instructions missing?

### ISSUE THREAD

**Issue by kamchy** [knes1/kotao#1]
Hello, 
after cloning kotao sources and building with _./gradlew build_, I cannot find kotao / kotao.bat scripts. Are those files missing or should I generate them in some other way? Could you please add "Build from sources" instructions" section to README ?

**Comment by knes1** [comment]
Ok - will add the instructions;

In the meantime, to get the scripts do the following:

`./gradlew distZip`

Then take a look at `build/distributions/kotao.zip`

**Comment by knes1** [comment]
PS.

The distZip task was added only recently (yesterday) so make sure you have the latest version pulled from master.

**Comment by kamchy** [comment]
Great! Thanks!
